data:
  source_train: "PLEIADES"
  dataset: "OBJECTDETECTION"
  dataset_test: "OBJECTDETECTION"
  task: "detection"
  year: [2022]
  dep: ["976"]
  type_labeler: "BDTOPO"
  buffer_size: 10
  n_channels_train: 3
  n_bands: 3
  tile_size: 125
  augmentation: True
  num_workers: 5
  prop: 1

optim:
  loss: "crossentropy"
  lr: 0.00003
  momentum: 0.7
  module: "fasterrcnn"
  batch_size: 8
  batch_size_test: 8
  max_epochs: 200
  val_prop: 0.2
  accumulate_batch : 8
  monitor: "validation_accuracy"
  mode: "max"
  patience: 200
  scheduler_patience: 10
  num_sanity_val_steps: 2

mlflow: True
