donnees:
  source train: "PLEIADES"
  dataset: "CHANGEISEVERYWHERE" 
  dataset-test: "CHANGEDETECTIONDATASET"
  year: [2022]
  dep: ["972"]
  type labeler: "BDTOPO"
  buffer size: 10
  n channels train: 6
  n bands: 3
  tile size: 250
  augmentation: False
  task: "change-detection"
  prop: 1

optim:
  loss: "crossentropy"
  lr: 0.0001
  momentum: 0.9
  module: "resnet50"
  batch size: 9
  batch size test: 100
  max epochs: 20
  val prop: 0.2
  accumulate batch : 8

mlflow: True
