data:
  source_train: "PLEIADES"
  dataset: "PLEIADE"
  dataset_test: "PLEIADE"
  task: "segmentation"
  year: [2022]
  dep: ["dummy"]
  type_labeler: "BDTOPO"
  buffer_size: 10
  n_channels_train: 3
  n_bands: 3
  tile_size: 125
  augmentation: True
  num_workers: 5
  prop: 1

optim:
  loss: "crossentropy"
  lr: 0.001
  momentum: 0.9
  module: "deeplabv3"
  batch_size: 4
  batch_size_test: 4
  max_epochs: 200
  val_prop: 0.2
  accumulate_batch : 8
  monitor: "validation_accuracy"
  mode: "max"
  patience: 35
  scheduler_patience: 10
  num_sanity_val_steps: 2

mlflow: True
