data:
  source_train: "SENTINEL1-2"
  dataset: "SENTINEL"
  dataset_test: "SENTINEL"
  task: "segmentation"

  millesime:
    - dep: 976
      year: 2022
    - dep: 975
      year: 2022
  type_labeler: "BDTOPO"
  buffer_size: 10
  n_channels_train: 13
  n_bands: 13
  tile_size: 125
  augmentation: True
  num_workers: 5
  prop: 1

optim:
  loss: "crossentropy"
  lr: 0.0001
  momentum: 0.9
  module: "deeplabv3"
  batch_size: 5
  batch_size_test: 4
  max_epochs: 2
  val_prop: 0.2
  accumulate_batch : 8
  monitoring:
    checkpoints:
    - monitor: validation_loss
      save_top_k: 1
      save_last: True
      mode: min
    - monitor: validation_IOU
      save_top_k: 1
      save_last: True
      mode: max
    earlystop:
      monitor: validation_loss
      patience: 5
      mode: min

mlflow: False
