donnees:
  source train: "SENTINEL1-2"
  dataset: "SENTINEL"
  year: [2022]
  dep: ["972"]
  type labeler: "BDTOPO"
  buffer size: 10
  n channels train: 13
  n bands: 13
  tile size: 250
  augmentation: True
  task: "segmentation"

optim:
  loss: "lossbinaire"
  lr: 0.0001
  momentum: 0.9
  module: "binarydeeplabv3"
  batch size: 9
  batch size test: 4
  max epochs: 50
  val prop: 0.2
  accumulate batch : 3

mlflow: True
