donnees:
  source train: "PLEIADES"
  dataset: "PLEIADE" 
  dataset-test: "PLEIADE"
  year: [2022, 2017]
  dep: ["972", "976"]
  type labeler: "BDTOPO"
  mask inversion threshold: [140, 95]
  buffer size: 10
  n channels train: 3
  n bands entry: 3
  n bands: 3
  tile size: 250
  augmentation: False
  task: "segmentation"
  max size ones: 30000
  prop: 0.00

optim:
  loss: "softiou"
  lr: 0.0001
  momentum: 0.9
  module: "deeplabv3"
  batch size: 9
  batch size test: 4
  max epochs: 100
  val prop: 0.2
  accumulate batch : 3

mlflow: True