data:
  source_train: "PLEIADES"
  dataset: "PLEIADE"
  dataset_test: "PLEIADE"
  task: "segmentation"
  percent_keep: 0.01

  millesime:
    - dep: "976"
      year: "2022"


  type_labeler: "BDTOPO"
  buffer_size: 10
  n_channels_train: 3
  n_bands: 3
  tile_size: 125
  augmentation: True
  prop: 1

optim:
  loss: "crossentropy"
  lr: 0.001
  momentum: 0.9
  module: "deeplabv3"
  batch_size: 4
  batch_size_test: 4
  max_epochs: 2
  val_prop: 0.2
  accumulate_batch : 8
  monitoring:
    checkpoints:
    - monitor: validation_loss
      save_top_k: 1
      save_last: True
      mode: min
    - monitor: validation_IOU
      save_top_k: 1
      save_last: True
      mode: max
    earlystop:
      monitor: validation_loss
      patience: 5
      mode: min
  scheduler_patience: 10
  num_sanity_val_steps: 2
