donnees:
  source train: "PLEIADES"
  dataset: "CLASSIFICATION" 
  dataset-test: "CLASSIFICATION"
  year: [2022]
  dep: ["972"]
  type labeler: "BDTOPO"
  buffer size: 10
  n channels train: 3
  n bands entry: 3
  n bands: 3
  tile size: 250
  augmentation: False
  task: "classification"
  max size ones: 15000
  prop: 1

optim:
  loss: "lossbinaire"
  lr: 0.0001
  momentum: 0.9
  module: "resnet50"
  batch size: 8
  batch size test: 8
  max epochs: 20
  val prop: 0.2
  accumulate batch : 3

mlflow: True