donnees:
  source_train: "PLEIADES"
  dataset: "object_detection"
  dataset_test: "CHANGEDETECTIONDATASET"
  task: "detection"
  year: [2022]
  dep: ["972"]
  type_labeler: "BDTOPO"
  buffer_size: 10
  n_channels_train: 6
  n_bands: 3
  tile_size: 250
  augmentation: True
  num_workers: 5
  prop: 1

optim:
  loss: "crossentropy"
  lr: 0.0001
  momentum: 0.9
  module: "fasterrcnn"
  batch_size: 5
  batch_size_test: 100
  max_epochs: 5
  val_prop: 0.2
  accumulate_batch : 8
  monitor: "validation_accuracy"
  mode: "min"
  patience: 10

mlflow: True
