donnees:
  source train: "SENTINEL1-2"
  dataset: "SENTINEL"
  dataset-test: "SENTINEL"
  year: [2021, 2022]
  dep: ["972", "972"]
  type labeler: "BDTOPO"
  buffer size: 10
  n channels train: 14
  n bands entry: 14
  n bands: 14
  tile size: 125
  augmentation: False
  task: "segmentation"
  prop: 0.05

optim:
  loss: "crossentropyselmade"
  lr: 0.003
  momentum: 0.9
  module: "deeplabv3"
  optimizer: "Adam"
  scheduler: "OneCycleLR"
  batch size: 50
  batch size test: 16
  max epochs: 2
  val prop: 0.2
  accumulate batch : 4

mlflow: True