donnees:
  source train: "PLEIADES"
  dataset: "CLASSIFICATION" 
  year: [2022]
  dep: ["972"]
  type labeler: "RIL"
  buffer size: 10
  n channels train: 3
  n bands: 3
  tile size: 50
  augmentation: False
  task: "classification"

optim:
  loss: "lossbinaire"
  lr: 0.0001
  momentum: 0.9
  module: "resnet50"
  batch size: 225
  batch size test: 100
  max epochs: 50
  val prop: 0.2
  accumulate batch : 3

mlflow: True
