donnees:
  source train: "SENTINEL1-2"
  dataset: "CLASSIFICATION"
  dataset-test: "CLASSIFICATION"
  year: [2021, 2021, 2021, 2022, 2022, 2022]
  dep: ["971", "972", "974", "971", "972", "974"]
  type labeler: "BDTOPO"
  buffer size: 10
  n channels train: 13
  n bands entry: 13
  n bands: 13
  tile size: 100
  augmentation: False
  task: "classification"
  prop: 1

optim:
  loss: "lossbinaire"
  lr: 0.0015
  momentum: 0.9
  module: "resnet50"
  batch size: 30
  batch size test: 2
  max epochs: 100
  val prop: 0.2
  accumulate batch : 3

mlflow: True