donnees:
  source train: "PLEIADE"
  year: [2022]
  dep: ["972"]
  type labeler: "RIL"
  buffer size: 10
  n channels train: 3
  tile size: 250

optim:
  lr: 0.0001
  momentum: 0.9
  module: "deeplabv3"
  batch size: 2
  max epochs: 100
