donnees:
  source train: "PLEIADES"
  dataset: "PLEIADE"
  year: [2022]
  dep: ["972"]
  type labeler: "RIL"
  buffer size: 10
  n channels train: 3
  n bands: 3
  tile size: 250
  augmentation: True
  task: "segmentation"

optim:
  loss: "crossentropy"
  lr: 0.0001
  momentum: 0.9
  module: "deeplabv3"
  batch size: 10
  batch size test: 4
  max epochs: 2
  val prop: 0.2

mlflow: True
