donnees:
  source train: "S2Looking"
  dataset: "CHANGEDETECTIONDATASETS2" 
  dataset-test: "CHANGEDETECTIONDATASETS2"
  year: "NA"
  dep: "NA"
  type labeler: "NA"
  buffer size: "NA"
  n channels train: 6
  n bands: 3
  tile size: 250
  augmentation: True
  task: "change-detection"
  prop: "NA"
  num_workers: 0

optim:
  loss: "crossentropyselmade"
  lr: 0.01
  momentum: 0.9
  module: "deeplabv3"
  batch size: 5
  batch size test: 4
  max epochs: 100
  val prop: 0.2
  accumulate batch : 2

mlflow: True