donnees:
  source train: "PLEIADES"
  dataset: "changeIsEverywhere"
  year: [2022]
  dep: ["972"]
  type labeler: "BDTOPO"
  buffer size: 10
  n channels train: 6
  n bands: 3
  tile size: 250
  augmentation: True

optim:
  loss: "crossentropy"
  lr: 0.0001
  momentum: 0.9
  module: "deeplabv3"
  batch size: 5
  max epochs: 100
  val prop: 0.2

mlflow: False
