project:
  type: book

book:
  repo-subdir: website
  repo-url: https://github.com/InseeFrLab/detection-bidonvilles
  title: Slum detection like a boss
  author:
  - name: Shiraz Adamaly
    email: shiraz.adamaly@insee.fr
  - name: Raya Berova
    email: raya.berova@insee.fr
  - name: Thomas Faria
    email: thomas.faria@insee.fr
  - name: Clément Guillo
    email: clement.guillo@insee.fr
  - name: Judith Nabec
    email: judith.nabec@insee.fr
  - name: Tom Seimandi
    email: tom.seimandi@insee.fr

  date: last-modified
  chapters:
    - index.qmd
    - 1-Introduction.qmd
    - 2-Image-input.qmd
    - text: "---"
    - references.qmd
  appendices:
    - A-Appendix1.qmd

  downloads: [pdf]

bibliography: bibliography.bib

format:
  html:
    theme: cosmo
    reference-location: margin
    fig-align: center

  # pdf:
  #   keep-tex: false
  #   toc: true
  #   toc-title: Contents
  #   fig-pos: 'H'
  #   fig-align: center


editor: visual
