on:
  workflow_dispatch:
  push:
    branches: 
      - 'main'
    paths:
      - 'website/'

name: Quarto Publish

jobs:
  publish-website:
    runs-on: ubuntu-latest

    permissions:
      contents: write
    steps:

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install Latex
        run:  quarto install tinytex

      - name: Install Minio Client
        run: |
          wget -q https://dl.min.io/client/mc/release/linux-amd64/mc -O /usr/local/bin/mc
          chmod +x /usr/local/bin/mc
          export 
  
      - name: copy pictures from minio
        uses: |
          export MC_HOST_s3=https://$AWS_ACCESS_KEY_ID:$AWS_SECRET_ACCESS_KEY@$AWS_S3_ENDPOINT
          mc cp --recursive s3/projet-slums-detection/Quarto/ website/figures
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_S3_ENDPOINT: ${{ secrets.AWS_S3_ENDPOINT }}
          

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: website/
     