on:
  workflow_dispatch:
  push:
    branches: main
    paths:
      - website/

name: Quarto Publish

jobs:
  publish-website:
    runs-on: ubuntu-latest

    permissions:
      contents: write
    steps:

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install Latex
        run:  quarto install tinytex

      - name: copy pictures from minio
        uses: mc cp --recursive s3/projet-slums-detection/Quarto website/figures

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: website/
     